name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: test
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MONGODB_URI: ${{ secrets.MONGODB_URI || 'mongodb://localhost:27017/test' }}
  PORT: 3000

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    # Backend
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Run backend tests
      working-directory: ./backend
      run: npm test
      env:
        MONGODB_URI: ${{ env.MONGODB_URI }}
        JWT_SECRET: ${{ env.JWT_SECRET }}
        NODE_ENV: ${{ env.NODE_ENV }}
    
    # Frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test
      env:
        NODE_ENV: test
    
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

  # Add deployment steps here when ready
  # deploy-staging:
  #   needs: test-and-build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: echo "Deploy to staging"
  #     # Add your deployment commands here
